version: "3.9"
services:
  postgres:
    image: postgres:9.6.0
    container_name: ${APP_NAME}.postgres
    environment:
      POSTGRES_DB: "ozon"
      POSTGRES_USER: "ozon"
      POSTGRES_PASSWORD: "ozon"
    ports: ["5432:5432"]

  redis:
    image: redis
    container_name: ${APP_NAME}.redis
    ports: ["6379:6379"]
    expose: ["6379"]